from ragnarok_expedition_pet import Gene, Part


class TacticService:
    def __init__(self):
        gene_list = [
            Gene(name="可愛小角", part=Part.HEAD),
            Gene(name="中分棕髮", part=Part.HEAD),
            Gene(name="白雪冰晶", part=Part.HEAD),
            Gene(name="紳士禮帽", part=Part.HEAD),
            Gene(name="幸運葉草", part=Part.HEAD),
            Gene(name="蒸蒸日上", part=Part.HEAD),
            Gene(name="羊毛線團", part=Part.BODY),
            Gene(name="針織圍巾", part=Part.BODY),
            Gene(name="格子襯衫", part=Part.BODY),
            Gene(name="閃耀冰方", part=Part.BODY),
            Gene(name="青綠樹枝", part=Part.BODY),
            Gene(name="精鐵原石", part=Part.BODY),
            Gene(name="鋒利彎刀", part=Part.BACK),
            Gene(name="法國麵包", part=Part.BACK),
            Gene(name="雞毛撢子", part=Part.BACK),
            Gene(name="雲霧繚繞", part=Part.BACK),
            Gene(name="冰糖葫蘆", part=Part.BACK),
            Gene(name="回力骨鏢", part=Part.BACK),
            Gene(name="山羊犄角", part=Part.HEAD, children=["可愛小角", "中分棕髮"]),
            Gene(name="純淨觸角", part=Part.HEAD, children=["可愛小角", "白雪冰晶"]),
            Gene(name="墮天之環", part=Part.HEAD, children=["可愛小角", "蒸蒸日上"]),
            Gene(name="雪色銀絲", part=Part.HEAD, children=["中分棕髮", "白雪冰晶"]),
            Gene(name="一窩雜草", part=Part.HEAD, children=["中分棕髮", "幸運葉草"]),
            Gene(name="鯨泉湧動", part=Part.HEAD, children=["中分棕髮", "蒸蒸日上"]),
            Gene(name="皇帝新帽", part=Part.HEAD, children=["白雪冰晶", "紳士禮帽"]),
            Gene(name="六月飛雪", part=Part.HEAD, children=["蒸蒸日上", "白雪冰晶"]),
            Gene(name="四星大廚", part=Part.HEAD, children=["紳士禮帽", "蒸蒸日上"]),
            Gene(name="天使光環", part=Part.HEAD, children=["幸運葉草", "蒸蒸日上"]),
            Gene(name="白色鬍鬚", part=Part.BODY, children=["羊毛線團", "針織圍巾"]),
            Gene(name="華貴金線", part=Part.BODY, children=["羊毛線團", "閃耀冰方"]),
            Gene(name="龐克潮流", part=Part.BODY, children=["羊毛線團", "精鐵原石"]),
            Gene(name="藤條綑綁", part=Part.BODY, children=["針織圍巾", "青綠樹枝"]),
            Gene(name="禦鐵王座", part=Part.BODY, children=["針織圍巾", "精鐵原石"]),
            Gene(name="熱帶草裙", part=Part.BODY, children=["格子襯衫", "青綠樹枝"]),
            Gene(name="鎖鏈鐵甲", part=Part.BODY, children=["格子襯衫", "精鐵原石"]),
            Gene(name="青蘋果凍", part=Part.BODY, children=["閃耀冰方", "青綠樹枝"]),
            Gene(name="耀鏡立方", part=Part.BODY, children=["閃耀冰方", "精鐵原石"]),
            Gene(name="苔蘚石球", part=Part.BODY, children=["精鐵原石", "青綠樹枝"]),
            Gene(name="收割鐮刀", part=Part.BACK, children=["鋒利彎刀", "法國麵包"]),
            Gene(name="雙刃精通", part=Part.BACK, children=["鋒利彎刀", "雲霧繚繞"]),
            Gene(name="拐棍糖杖", part=Part.BACK, children=["鋒利彎刀", "冰糖葫蘆"]),
            Gene(name="才藝展示", part=Part.BACK, children=["鋒利彎刀", "回力骨鏢"]),
            Gene(name="動人音符", part=Part.BACK, children=["法國麵包", "雲霧繚繞"]),
            Gene(name="潔白羽翼", part=Part.BACK, children=["雞毛撢子", "雲霧繚繞"]),
            Gene(name="精靈羽翼", part=Part.BACK, children=["雞毛撢子", "冰糖葫蘆"]),
            Gene(name="動力滑板", part=Part.BACK, children=["雲霧繚繞", "回力骨鏢"]),
            Gene(name="環保垃圾", part=Part.BACK, children=["冰糖葫蘆", "回力骨鏢"]),
            Gene(name="櫻色貝雷", part=Part.HEAD, children=["可愛小角", "紳士禮帽"]),
            Gene(name="生命冠冕", part=Part.HEAD, children=["可愛小角", "幸運葉草"]),
            Gene(name="飄逸秀髮", part=Part.HEAD, children=["中分棕髮", "紳士禮帽"]),
            Gene(name="靈光乍現", part=Part.HEAD, children=["白雪冰晶", "幸運葉草"]),
            Gene(name="幸福小帽", part=Part.HEAD, children=["紳士禮帽", "幸運葉草"]),
            Gene(name="白淨襯衣", part=Part.BODY, children=["羊毛線團", "格子襯衫"]),
            Gene(name="翠綠包菜", part=Part.BODY, children=["羊毛線團", "青綠樹枝"]),
            Gene(name="雙色披風", part=Part.BODY, children=["針織圍巾", "格子襯衫"]),
            Gene(name="大汗淋漓", part=Part.BODY, children=["針織圍巾", "閃耀冰方"]),
            Gene(name="幻想魔方", part=Part.BODY, children=["格子襯衫", "閃耀冰方"]),
            Gene(name="刀鋒羽翼", part=Part.BACK, children=["鋒利彎刀", "雞毛撢子"]),
            Gene(name="流星鐵鎚", part=Part.BACK, children=["法國麵包", "雞毛撢子"]),
            Gene(name="遠行行囊", part=Part.BACK, children=["法國麵包", "冰糖葫蘆"]),
            Gene(name="獵人烤肉", part=Part.BACK, children=["法國麵包", "回力骨鏢"]),
            Gene(name="暗黑羽翼", part=Part.BACK, children=["雞毛撢子", "回力骨鏢"]),
            Gene(name="溜波波利", part=Part.BACK, children=["雲霧繚繞", "冰糖葫蘆"]),
            Gene(name="歐麥波利", part=Part.FINAL, children=["天使光環", "藤條捆綁", "潔白羽翼"]),
            Gene(name="上流波利", part=Part.FINAL, children=["靈光乍現", "耀鏡立方", "溜波波利"]),
            Gene(name="歌劇魅利", part=Part.FINAL, children=["六月飛雪", "大汗淋漓", "動人音符"]),
            Gene(name="波利酋長", part=Part.FINAL, children=["幸福小帽", "翠綠包菜", "流星鏈鎚"]),
            Gene(name="廚神波利", part=Part.FINAL, children=["四星大廚", "翠綠包菜", "獵人烤肉"]),
            Gene(name="機利飛升", part=Part.FINAL, children=["天使光環", "耀鏡立方", "刀鋒羽翼"]),
            Gene(name="巴風特利", part=Part.FINAL, children=["山羊犄角", "白色鬍鬚", "收割鐮刀"]),
            Gene(name="七彩獨角利", part=Part.FINAL, children=["純淨獨角", "幻想魔方", "潔白羽翼"]),
            Gene(name="潮色鹽辛利", part=Part.FINAL, children=["櫻色貝雷", "白淨襯衣", "動力滑板"]),
            Gene(name="生命波神", part=Part.FINAL, children=["生命冠冕", "藤條捆綁", "精靈羽翼"]),
            Gene(name="深闇幻利", part=Part.FINAL, children=["墮天之環", "龐克潮流", "暗黑羽翼"]),
            Gene(name="詐欺波神", part=Part.FINAL, children=["山羊犄角", "禦鐵王座", "雙刃精通"]),
            Gene(name="重金屬搖利", part=Part.FINAL, children=["純淨獨角", "龐克潮流", "動人音符"]),
            Gene(name="怪盜波德", part=Part.FINAL, children=["櫻色貝雷", "雙色披風", "拐棍糖杖"]),
            Gene(name="玩偶小利", part=Part.FINAL, children=["生命冠冕", "青蘋果凍", "才藝展示"]),
            Gene(name="暗黑破壞利", part=Part.FINAL, children=["墮天之環", "禦鐵王座", "刀鋒羽翼"]),
            Gene(name="利尼泰美", part=Part.FINAL, children=["雪色銀絲", "白淨襯衣", "流星鏈鎚"]),
            Gene(name="黑酷劍利", part=Part.FINAL, children=["飄逸秀髮", "鎖鏈鐵甲", "雙刃精通"]),
            Gene(name="邋利邋遢", part=Part.FINAL, children=["一窩雜草", "熱帶草裙", "遠行行囊"]),
            Gene(name="桑拿波利", part=Part.FINAL, children=["鯨泉湧動", "大汗淋漓", "溜波波利"]),
            Gene(name="見波卸甲", part=Part.FINAL, children=["皇帝新帽", "鎖鏈鐵甲", "遠行行囊"]),
            Gene(name="雙面利", part=Part.FINAL, children=["雪色銀絲", "雙色披風", "暗黑羽翼"]),
            Gene(name="利后", part=Part.FINAL, children=["飄逸秀髮", "青蘋果凍", "精靈羽翼"]),
            Gene(name="原始野蠻利", part=Part.FINAL, children=["一窩雜草", "苔蘚石球", "獵人烤肉"]),
            Gene(name="利攀浪峰", part=Part.FINAL, children=["鯨泉湧動", "熱帶草裙", "動力滑板"]),
            Gene(name="石波利", part=Part.FINAL, children=["皇帝新帽", "苔蘚石球", "獵人烤肉"]),
            Gene(name="天才發明利", part=Part.FINAL, children=["靈光乍現", "幻想魔方", "環保垃圾"]),
            Gene(name="聖誕老波", part=Part.FINAL, children=["六月飛雪", "白色鬍鬚", "拐棍糖杖"]),
            Gene(name="潮利達人", part=Part.FINAL, children=["幸福小帽", "華貴金線", "才藝展示"]),
            Gene(name="關東煮仙波", part=Part.FINAL, children=["四星大廚", "華貴金線", "環保垃圾"])
        ]

        self.__genes = {}

        for gene in gene_list:
            self.__genes[gene.name] = gene

    def search(self, gene_name):
        gene = self.__genes.get(gene_name)

        return gene if gene is not None else "Not found"
